Repository bookwhale/bookwhale-server, pull requests merged in 2021-12, with the labels that each got.

#69 Issue/gentledot/62,67 - 판매글 및 판매글 목록 조회, 등록, 수정 기능 수정작업 반영
  api/src/main/java/com/bookwhale/post/dto/PostRequest.java
  api/src/main/java/com/bookwhale/post/dto/PostStatusUpdateRequest.java
  api/src/main/java/com/bookwhale/post/dto/PostUpdateRequest.java
  api/src/main/java/com/bookwhale/post/dto/PostsRequest.java
  api/src/main/java/com/bookwhale/post/dto/PostsResponse.java
  api/src/main/java/com/bookwhale/post/service/PostService.java
  api/src/test/java/com/bookwhale/chatroom/acceptance/ChatRoomAcceptanceTest.java
  api/src/test/java/com/bookwhale/post/acceptance/PostAcceptanceTest.java
  api/src/test/java/com/bookwhale/post/acceptance/step/PostAcceptanceStep.java
  api/src/test/java/com/bookwhale/post/controller/PostControllerTest.java
  api/src/test/java/com/bookwhale/post/docs/PostDocumentation.java
  api/src/test/java/com/bookwhale/post/service/PostServiceTest.java
  api/src/test/java/com/bookwhale/user/acceptance/UserAcceptanceTest.java
  api/src/test/java/com/bookwhale/user/acceptance/step/UserAcceptanceStep.java
  api/src/test/java/com/bookwhale/user/controller/LikeControllerTest.java
  api/src/test/java/com/bookwhale/user/controller/UserControllerTest.java
  api/src/test/java/com/bookwhale/user/docs/UserDocumentation.java
  api/src/test/java/com/bookwhale/user/service/LikeServiceTest.java
  core/src/main/java/com/bookwhale/post/domain/PostCustomRepository.java
  core/src/main/java/com/bookwhale/post/domain/PostCustomRepositoryImpl.java
  core/src/main/java/com/bookwhale/post/domain/PostStatus.java
  core/src/test/java/com/bookwhale/post/domain/PostRepositoryTest.java
Labels: refactor, fix

#74 issue/70 - [리팩토링] 프로젝트 리뉴얼
  api/src/main/java/com/bookwhale/article/controller/ArticleController.java
  api/src/main/java/com/bookwhale/article/service/ArticleService.java
  api/src/main/java/com/bookwhale/chatroom/service/ChatRoomService.java
  api/src/main/java/com/bookwhale/common/mail/MailHandler.java
  api/src/main/java/com/bookwhale/common/mail/SmtpMailSender.java
  api/src/main/java/com/bookwhale/config/security/SecurityConfig.java
  api/src/main/java/com/bookwhale/user/controller/UserController.java
  api/src/main/java/com/bookwhale/user/service/UserService.java
  api/src/test/java/com/bookwhale/article/acceptance/ArticleAcceptanceTest.java
  api/src/test/java/com/bookwhale/article/acceptance/step/ArticleAcceptanceStep.java
  api/src/test/java/com/bookwhale/article/controller/ArticleControllerTest.java
  api/src/test/java/com/bookwhale/article/docs/ArticleDocumentation.java
  api/src/test/java/com/bookwhale/chatroom/service/ChatRoomServiceTest.java
  api/src/test/java/com/bookwhale/common/mail/SmtpMailSenderTest.java
  api/src/test/java/com/bookwhale/user/acceptance/UserAcceptanceTest.java
  api/src/test/java/com/bookwhale/user/acceptance/step/UserAcceptanceStep.java
  api/src/test/java/com/bookwhale/user/controller/UserControllerTest.java
  api/src/test/java/com/bookwhale/user/docs/UserDocumentation.java
  api/src/test/java/com/bookwhale/user/service/UserServiceTest.java
  api/src/test/resources/logback-test.xml
Labels: backend, refactor

#78 issue/75 - [판매글] 판매글, 내 판매글, 관심 판매글 목록 조회 API 변경
  api/src/main/java/com/bookwhale/article/controller/ArticleController.java
  api/src/main/java/com/bookwhale/article/dto/ArticlesRequest.java
  api/src/main/java/com/bookwhale/article/dto/ArticlesResponse.java
  api/src/main/java/com/bookwhale/article/service/ArticleService.java
  api/src/main/java/com/bookwhale/user/dto/FavoriteResponse.java
  api/src/test/java/com/bookwhale/article/acceptance/ArticleAcceptanceTest.java
  api/src/test/java/com/bookwhale/article/acceptance/step/ArticleAcceptanceStep.java
  api/src/test/java/com/bookwhale/article/controller/ArticleControllerTest.java
  api/src/test/java/com/bookwhale/article/docs/ArticleDocumentation.java
  api/src/test/java/com/bookwhale/user/controller/FavoriteControllerTest.java
  api/src/test/java/com/bookwhale/user/docs/UserDocumentation.java
  core/src/main/java/com/bookwhale/article/domain/Article.java
  core/src/main/java/com/bookwhale/article/domain/ArticleCustomRepository.java
  core/src/main/java/com/bookwhale/article/domain/ArticleCustomRepositoryImpl.java
  core/src/test/java/com/bookwhale/article/domain/ArticleRepositoryTest.java
Labels: backend

#79 Issue/73 OAuth 로그인 구현
  api/build.gradle
  api/src/main/java/com/bookwhale/auth/controller/OAuthController.java
  api/src/main/java/com/bookwhale/auth/domain/CurrentUser.java
  api/src/main/java/com/bookwhale/auth/domain/OAuthObjectConverter.java
  api/src/main/java/com/bookwhale/auth/domain/info/UserInfo.java
  api/src/main/java/com/bookwhale/auth/domain/info/UserInfoFromGoogle.java
  api/src/main/java/com/bookwhale/auth/domain/info/UserInfoFromNaver.java
  api/src/main/java/com/bookwhale/auth/domain/info/UserInfoFromToken.java
  api/src/main/java/com/bookwhale/auth/domain/provider/GoogleOAuthProvider.java
  api/src/main/java/com/bookwhale/auth/domain/provider/NaverOAuthProvider.java
  api/src/main/java/com/bookwhale/auth/domain/provider/OAuthProvider.java
  api/src/main/java/com/bookwhale/auth/domain/provider/OAuthProviderType.java
  api/src/main/java/com/bookwhale/auth/domain/token/GoogleOAuthToken.java
  api/src/main/java/com/bookwhale/auth/domain/token/NaverOAuthToken.java
  api/src/main/java/com/bookwhale/auth/domain/token/OAuthToken.java
  api/src/main/java/com/bookwhale/auth/dto/OAuthLoginResponse.java
  api/src/main/java/com/bookwhale/auth/dto/OAuthProviderTypeConverter.java
  api/src/main/java/com/bookwhale/auth/dto/OAuthRefreshLoginRequest.java
  api/src/main/java/com/bookwhale/auth/dto/OAuthTokenExtractor.java
  api/src/main/java/com/bookwhale/auth/service/OauthService.java
  api/src/main/java/com/bookwhale/common/token/JWT.java
  api/src/main/java/com/bookwhale/common/utils/RandomUtils.java
  api/src/main/java/com/bookwhale/config/ApiConfig.java
  api/src/main/java/com/bookwhale/config/CurrentUserArgumentResolver.java
  api/src/main/java/com/bookwhale/config/WebMvcConfig.java
  api/src/main/java/com/bookwhale/config/security/SecurityConfig.java
  api/src/main/java/com/bookwhale/config/security/WebMvcConfig.java
  core/src/main/java/com/bookwhale/auth/domain/Token.java
  core/src/main/java/com/bookwhale/auth/domain/TokenRepository.java
  core/src/main/java/com/bookwhale/common/exception/ErrorCode.java
  core/src/main/java/com/bookwhale/user/domain/ApiUser.java
Labels: backend, feature

#91 Refactor/87 - OAuth 단위테스트 추가 (controller), Spring REST Docs 보완
  api/src/docs/asciidoc/api-docs.adoc
  api/src/main/java/com/bookwhale/auth/controller/OAuthController.java
  api/src/main/java/com/bookwhale/auth/dto/OAuthResultResponse.java
  api/src/main/java/com/bookwhale/auth/service/OauthService.java
  api/src/test/java/com/bookwhale/auth/controller/OAuthControllerTest.java
  api/src/test/java/com/bookwhale/auth/docs/OAuthDocumentation.java
Labels: documentation, backend
